<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use DB;
use Carbon\Carbon;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('fragrances')->insert([
            ['theLoai' => 'Fresh'],
            ['theLoai' => 'Fruity'],
            ['theLoai' => 'Sweet'],
            ['theLoai' => 'Woody'],
            ['theLoai' => 'Floral'],
        ]);
     
        DB::table('products')->insert([
            ['loaiSanPham' => 'single wick candle', 'tenSanPham' => 'Winter Candy Apple', 'muiHuong' => 'red apples, crisp pears and candied oranges', 'loaiMuiHuong' => 2, 'nhaCungCap' => rand(1,6), 'trongLuong' => rand(1, 10) * 100, 'moTa' => 'Have a small room that needs some fragrance goodness…or want to give a totally new scent a try? That where our single wick candles come in. Perfect for the bathroom, kitchen or anywhere else that needs a boost, these scented candles fill up the room with major fragrance…even though they come in a smaller package. We are also super into aromatherapy candles for a little end-of-the-day relaxation. Grab your favorite scent or choose one based on your mood and prepare to feel amazing.', 'image_path' => '1.webp', 'giaNhap' => '100000', 'giaBan' => '250000', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['loaiSanPham' => 'single wick candle', 'tenSanPham' => 'Tree Farm', 'muiHuong' => 'rcrisp pine needle, warm cedar and spiced apple', 'loaiMuiHuong' => 4, 'nhaCungCap' => rand(1,6), 'trongLuong' => rand(1, 10) * 100, 'moTa' => 'Have a small room that needs some fragrance goodness…or want to give a totally new scent a try? That where our single wick candles come in. Perfect for the bathroom, kitchen or anywhere else that needs a boost, these scented candles fill up the room with major fragrance…even though they come in a smaller package. We are also super into aromatherapy candles for a little end-of-the-day relaxation. Grab your favorite scent or choose one based on your mood and prepare to feel amazing.', 'image_path' => '2.webp', 'giaNhap' => '100000', 'giaBan' => '250000', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['loaiSanPham' => 'single wick candle', 'tenSanPham' => 'Tis The Season', 'muiHuong' => 'rich red apple, sweet cinnamon and cedarwood', 'loaiMuiHuong' => 3, 'nhaCungCap' => rand(1,6), 'trongLuong' => rand(1, 10) * 100, 'moTa' => 'Have a small room that needs some fragrance goodness…or want to give a totally new scent a try? That where our single wick candles come in. Perfect for the bathroom, kitchen or anywhere else that needs a boost, these scented candles fill up the room with major fragrance…even though they come in a smaller package. We are also super into aromatherapy candles for a little end-of-the-day relaxation. Grab your favorite scent or choose one based on your mood and prepare to feel amazing.', 'image_path' => '3.webp', 'giaNhap' => '100000', 'giaBan' => '250000', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['loaiSanPham' => 'single wick candle', 'tenSanPham' => 'Into The Night', 'muiHuong' => 'raspberry noir, amber crystals, velvety rose petals, creamy patchouli and mocha musk.', 'loaiMuiHuong' => 1, 'nhaCungCap' => rand(1,6), 'trongLuong' => rand(1, 10) * 100, 'moTa' => 'Have a small room that needs some fragrance goodness…or want to give a totally new scent a try? That where our single wick candles come in. Perfect for the bathroom, kitchen or anywhere else that needs a boost, these scented candles fill up the room with major fragrance…even though they come in a smaller package. We are also super into aromatherapy candles for a little end-of-the-day relaxation. Grab your favorite scent or choose one based on your mood and prepare to feel amazing.', 'image_path' => '4.webp', 'giaNhap' => '100000', 'giaBan' => '250000', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['loaiSanPham' => 'single wick candle', 'tenSanPham' => 'Warm Vanilla Sugar', 'muiHuong' => 'intoxicating vanilla, white orchid, sparkling sugar, fresh jasmine and creamy sandalwood', 'loaiMuiHuong' => 3, 'nhaCungCap' => rand(1,6), 'trongLuong' => rand(1, 10) * 100, 'moTa' => 'Have a small room that needs some fragrance goodness…or want to give a totally new scent a try? That where our single wick candles come in. Perfect for the bathroom, kitchen or anywhere else that needs a boost, these scented candles fill up the room with major fragrance…even though they come in a smaller package. We are also super into aromatherapy candles for a little end-of-the-day relaxation. Grab your favorite scent or choose one based on your mood and prepare to feel amazing.', 'image_path' => '5.webp', 'giaNhap' => '100000', 'giaBan' => '250000', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['loaiSanPham' => 'single wick candle', 'tenSanPham' => 'Merry Cookie', 'muiHuong' => 'fresh baked cookies, sparkling sugar crystals and rich vanilla', 'loaiMuiHuong' => 3, 'nhaCungCap' => rand(1,6), 'trongLuong' => rand(1, 10) * 100, 'moTa' => 'Have a small room that needs some fragrance goodness…or want to give a totally new scent a try? That where our single wick candles come in. Perfect for the bathroom, kitchen or anywhere else that needs a boost, these scented candles fill up the room with major fragrance…even though they come in a smaller package. We are also super into aromatherapy candles for a little end-of-the-day relaxation. Grab your favorite scent or choose one based on your mood and prepare to feel amazing.', 'image_path' => '6.webp', 'giaNhap' => '100000', 'giaBan' => '250000', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['loaiSanPham' => 'single wick candle', 'tenSanPham' => 'Winter', 'muiHuong' => ' white woods, pine needles, sparkling clementine and spiced clove', 'loaiMuiHuong' => 4, 'nhaCungCap' => rand(1,6), 'trongLuong' => rand(1, 10) * 100, 'moTa' => 'Have a small room that needs some fragrance goodness…or want to give a totally new scent a try? That where our single wick candles come in. Perfect for the bathroom, kitchen or anywhere else that needs a boost, these scented candles fill up the room with major fragrance…even though they come in a smaller package. We are also super into aromatherapy candles for a little end-of-the-day relaxation. Grab your favorite scent or choose one based on your mood and prepare to feel amazing.', 'image_path' => '7.webp', 'giaNhap' => '100000', 'giaBan' => '250000', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['loaiSanPham' => 'single wick candle', 'tenSanPham' => 'Japanese Cherry Blossom', 'muiHuong' => 'pear, Japanese cherry blossom and sandalwood', 'loaiMuiHuong' => 5, 'nhaCungCap' => rand(1,6), 'trongLuong' => rand(1, 10) * 100, 'moTa' => 'Have a small room that needs some fragrance goodness…or want to give a totally new scent a try? That where our single wick candles come in. Perfect for the bathroom, kitchen or anywhere else that needs a boost, these scented candles fill up the room with major fragrance…even though they come in a smaller package. We are also super into aromatherapy candles for a little end-of-the-day relaxation. Grab your favorite scent or choose one based on your mood and prepare to feel amazing.', 'image_path' => '8.webp', 'giaNhap' => '100000', 'giaBan' => '250000', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['loaiSanPham' => 'single wick candle', 'tenSanPham' => 'Blush Poinsettia', 'muiHuong' => ' rose petals, green ivy and sweet marshmallow', 'loaiMuiHuong' => 5, 'nhaCungCap' => rand(1,6), 'trongLuong' => rand(1, 10) * 100, 'moTa' => 'Have a small room that needs some fragrance goodness…or want to give a totally new scent a try? That where our single wick candles come in. Perfect for the bathroom, kitchen or anywhere else that needs a boost, these scented candles fill up the room with major fragrance…even though they come in a smaller package. We are also super into aromatherapy candles for a little end-of-the-day relaxation. Grab your favorite scent or choose one based on your mood and prepare to feel amazing.', 'image_path' => '9.webp', 'giaNhap' => '100000', 'giaBan' => '250000', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['loaiSanPham' => 'single wick candle', 'tenSanPham' => 'Butterfly', 'muiHuong' => 'raspberry nectar, iris petals and airy vanilla', 'loaiMuiHuong' => 5, 'nhaCungCap' => rand(1,6), 'trongLuong' => rand(1, 10) * 100, 'moTa' => 'Have a small room that needs some fragrance goodness…or want to give a totally new scent a try? That where our single wick candles come in. Perfect for the bathroom, kitchen or anywhere else that needs a boost, these scented candles fill up the room with major fragrance…even though they come in a smaller package. We are also super into aromatherapy candles for a little end-of-the-day relaxation. Grab your favorite scent or choose one based on your mood and prepare to feel amazing.', 'image_path' => '10.webp', 'giaNhap' => '100000', 'giaBan' => '250000', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            ['loaiSanPham' => '3 wick candle', 'tenSanPham' => 'Fresh Winter Air', 'muiHuong' => 'zesty citrus, fresh peppermint and cold evergreen', 'loaiMuiHuong' => 1, 'nhaCungCap' => rand(1,6), 'trongLuong' => rand(5, 10) * 100, 'moTa' => 'Have a small room that needs some fragrance goodness…or want to give a totally new scent a try? That where our single wick candles come in. Perfect for the bathroom, kitchen or anywhere else that needs a boost, these scented candles fill up the room with major fragrance…even though they come in a smaller package. We are also super into aromatherapy candles for a little end-of-the-day relaxation. Grab your favorite scent or choose one based on your mood and prepare to feel amazing.', 'image_path' => '11.webp', 'giaNhap' => '200000', 'giaBan' => '450000', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['loaiSanPham' => '3 wick candle', 'tenSanPham' => 'Sweater Weather', 'muiHuong' => 'fresh sage, juniper berry, aromatic eucalyptus and fresh woods', 'loaiMuiHuong' => 1, 'nhaCungCap' => rand(1,6), 'trongLuong' => rand(5, 10) * 100, 'moTa' => 'Have a small room that needs some fragrance goodness…or want to give a totally new scent a try? That where our single wick candles come in. Perfect for the bathroom, kitchen or anywhere else that needs a boost, these scented candles fill up the room with major fragrance…even though they come in a smaller package. We are also super into aromatherapy candles for a little end-of-the-day relaxation. Grab your favorite scent or choose one based on your mood and prepare to feel amazing.', 'image_path' => '12.webp', 'giaNhap' => '200000', 'giaBan' => '450000', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['loaiSanPham' => '3 wick candle', 'tenSanPham' => 'Saled Caramel', 'muiHuong' => ' roasted chestnuts, caramelized sugar and spiced rum', 'loaiMuiHuong' => 3, 'nhaCungCap' => rand(1,6), 'trongLuong' => rand(5, 10) * 100, 'moTa' => 'Have a small room that needs some fragrance goodness…or want to give a totally new scent a try? That where our single wick candles come in. Perfect for the bathroom, kitchen or anywhere else that needs a boost, these scented candles fill up the room with major fragrance…even though they come in a smaller package. We are also super into aromatherapy candles for a little end-of-the-day relaxation. Grab your favorite scent or choose one based on your mood and prepare to feel amazing.', 'image_path' => '13.webp', 'giaNhap' => '200000', 'giaBan' => '450000', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['loaiSanPham' => '3 wick candle', 'tenSanPham' => 'Champagne Toast', 'muiHuong' => 'bubbly champagne, sparkling berries and sweet orange', 'loaiMuiHuong' => 3, 'nhaCungCap' => rand(1,6), 'trongLuong' => rand(5, 10) * 100, 'moTa' => 'Have a small room that needs some fragrance goodness…or want to give a totally new scent a try? That where our single wick candles come in. Perfect for the bathroom, kitchen or anywhere else that needs a boost, these scented candles fill up the room with major fragrance…even though they come in a smaller package. We are also super into aromatherapy candles for a little end-of-the-day relaxation. Grab your favorite scent or choose one based on your mood and prepare to feel amazing.', 'image_path' => '14.webp', 'giaNhap' => '200000', 'giaBan' => '450000', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['loaiSanPham' => '3 wick candle', 'tenSanPham' => 'Harvest Gathering', 'muiHuong' => 'fresh picked apple, autumn berries and clove buds', 'loaiMuiHuong' => 2, 'nhaCungCap' => rand(1,6), 'trongLuong' => rand(5, 10) * 100, 'moTa' => 'Have a small room that needs some fragrance goodness…or want to give a totally new scent a try? That where our single wick candles come in. Perfect for the bathroom, kitchen or anywhere else that needs a boost, these scented candles fill up the room with major fragrance…even though they come in a smaller package. We are also super into aromatherapy candles for a little end-of-the-day relaxation. Grab your favorite scent or choose one based on your mood and prepare to feel amazing.', 'image_path' => '15.webp', 'giaNhap' => '200000', 'giaBan' => '450000', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            ['loaiSanPham' => 'essential oil', 'tenSanPham' => 'Blue Tansy Oil', 'muiHuong' => 'Fresh, mellow, balsamic', 'loaiMuiHuong' => 1, 'nhaCungCap' => rand(1,6), 'trongLuong' => rand(3, 8) * 100, 'moTa' => 'Possible skin sensitivity. Keep out of reach of children. If you are pregnant, nursing, or under a doctors care, consult your physician. Avoid contact with eyes, inner ears, and sensitive areas.', 'image_path' => '16.png', 'giaNhap' => '90000', 'giaBan' => '200000', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['loaiSanPham' => 'essential oil', 'tenSanPham' => 'Basil Oil', 'muiHuong' => 'Warm, spicy, herbal', 'loaiMuiHuong' => 2, 'nhaCungCap' => rand(1,6), 'trongLuong' => rand(3, 8) * 100, 'moTa' => 'Possible skin sensitivity. Keep out of reach of children. If you are pregnant, nursing, or under a doctors care, consult your physician. Avoid contact with eyes, inner ears, and sensitive areas.', 'image_path' => '17.png', 'giaNhap' => '80000', 'giaBan' => '190000', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['loaiSanPham' => 'essential oil', 'tenSanPham' => 'Bergamot Oil', 'muiHuong' => 'Sweet, citrusy', 'loaiMuiHuong' => 3, 'nhaCungCap' => rand(1,6), 'trongLuong' => rand(3, 8) * 100, 'moTa' => 'Possible skin sensitivity. Keep out of reach of children. If you are pregnant, nursing, or under a doctors care, consult your physician. Avoid contact with eyes, inner ears, and sensitive areas.', 'image_path' => '18.png', 'giaNhap' => '120000', 'giaBan' => '350000', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['loaiSanPham' => 'essential oil', 'tenSanPham' => 'Arborvitae Oil', 'muiHuong' => 'Woody, warm, earthy', 'loaiMuiHuong' => 4, 'nhaCungCap' => rand(1,6), 'trongLuong' => rand(3, 8) * 100, 'moTa' => 'Possible skin sensitivity. Keep out of reach of children. If you are pregnant, nursing, or under a doctors care, consult your physician. Avoid contact with eyes, inner ears, and sensitive areas.', 'image_path' => '19.png', 'giaNhap' => '240000', 'giaBan' => '550000', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['loaiSanPham' => 'essential oil', 'tenSanPham' => 'Clove Oil', 'muiHuong' => 'Spicy, warm, woody, floral', 'loaiMuiHuong' => 5, 'nhaCungCap' => rand(1,6), 'trongLuong' => rand(3, 8) * 100, 'moTa' => 'Possible skin sensitivity. Keep out of reach of children. If you are pregnant, nursing, or under a doctors care, consult your physician. Avoid contact with eyes, inner ears, and sensitive areas.', 'image_path' => '20.png', 'giaNhap' => '40000', 'giaBan' => '100000', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            ['loaiSanPham' => 'scented wax', 'tenSanPham' => 'Scented Wax Melts Lemongrass & Lime', 'muiHuong' => 'Lemongrass, Lime', 'loaiMuiHuong' => 1, 'nhaCungCap' => rand(1,6), 'trongLuong' => rand(3, 10) * 100, 'moTa' => 'Rich in lemon, artemisia, and cypress essential oils, this candle with its delicate and floral notes will offer a soft atmosphere in your home for up to 55 hours thanks to its unique wax assembly for a fragrant flicker true to the perfume concentrate. Made in France', 'image_path' => '21.jpg', 'giaNhap' => '100000', 'giaBan' => '300000', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['loaiSanPham' => 'scented wax', 'tenSanPham' => 'Scented Wax Melts Cinnamon & Orange', 'muiHuong' => 'Cinnamon, Orange', 'loaiMuiHuong' => 2, 'nhaCungCap' => rand(1,6), 'trongLuong' => rand(3, 10) * 100, 'moTa' => 'Rich in lemon, artemisia, and cypress essential oils, this candle with its delicate and floral notes will offer a soft atmosphere in your home for up to 55 hours thanks to its unique wax assembly for a fragrant flicker true to the perfume concentrate. Made in France', 'image_path' => '22.jpg', 'giaNhap' => '100000', 'giaBan' => '300000', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['loaiSanPham' => 'scented wax', 'tenSanPham' => 'Scented Wax Filled Votives', 'muiHuong' => 'Coconut & Vanilla', 'loaiMuiHuong' => 3, 'nhaCungCap' => rand(1,6), 'trongLuong' => rand(3, 10) * 100, 'moTa' => 'Rich in lemon, artemisia, and cypress essential oils, this candle with its delicate and floral notes will offer a soft atmosphere in your home for up to 55 hours thanks to its unique wax assembly for a fragrant flicker true to the perfume concentrate. Made in France', 'image_path' => '23.jpg', 'giaNhap' => '100000', 'giaBan' => '300000', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['loaiSanPham' => 'scented wax', 'tenSanPham' => 'Scented Wax Filled Votives Floral Cherry', 'muiHuong' => 'Coconut & Jasmine Cherry', 'loaiMuiHuong' => 4, 'nhaCungCap' => rand(1,6), 'trongLuong' => rand(3, 10) * 100, 'moTa' => 'Rich in lemon, artemisia, and cypress essential oils, this candle with its delicate and floral notes will offer a soft atmosphere in your home for up to 55 hours thanks to its unique wax assembly for a fragrant flicker true to the perfume concentrate. Made in France', 'image_path' => '24.jpg', 'giaNhap' => '200000', 'giaBan' => '500000', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['loaiSanPham' => 'scented wax', 'tenSanPham' => 'Scented Wax Filled Votives Chessbom', 'muiHuong' => 'Coconut & Lavender', 'loaiMuiHuong' => 5, 'nhaCungCap' => rand(1,6), 'trongLuong' => rand(3, 10) * 100, 'moTa' => 'Rich in lemon, artemisia, and cypress essential oils, this candle with its delicate and floral notes will offer a soft atmosphere in your home for up to 55 hours thanks to its unique wax assembly for a fragrant flicker true to the perfume concentrate. Made in France', 'image_path' => '25.jpg', 'giaNhap' => '500000', 'giaBan' => '700000', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
        ]);
    }
}
